CREATE DATABASE CGV_CLONE
GO

USE CGV_CLONE
GO


CREATE TABLE FILM
(
	ID INT IDENTITY(1000000,1),
	NAME NVARCHAR(100),
	PRICE FLOAT,
	DIRECTOR NVARCHAR(50),
	ACTOR NVARCHAR(200),
	CATEGORY NVARCHAR(200),
	DEBUT DATE,
	LANGUAGE NVARCHAR(100),
	RATED NVARCHAR(50),
)

CREATE TABLE CINEMA
(
	ID INT IDENTITY(2000000,1),
	NAME NVARCHAR(100),
	HOTLINE VARCHAR(15),
	ADDRESS NVARCHAR(100)
)

CREATE TABLE PERSON
(
	ID INT IDENTITY(3000000,1),
	NAME NVARCHAR(100),
	CITY NVARCHAR(50),
	ADDRESS NVARCHAR(100),
	GENDER BIT, --NAM = 1 ==TRUE, NỮ = 0 == FALSE
	DATEOFBIRTH DATE,
	EMAIL NVARCHAR(50)
)

CREATE TABLE ACCOUNT
(
	ACCNAME NVARCHAR(50),
	PASSWORD NVARCHAR(50),
)


